services:

  postgres:
    image: postgres:latest
    #    container_name: jakkarin-postgres
    environment:
      POSTGRES_DB: leave_system
      POSTGRES_USER: leave_user
      POSTGRES_PASSWORD: leavePassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ssodev -d ssotest"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: